# Generated by Django 5.2 on 2025-05-07 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metaphor', '0002_generationhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenerationHistory',
        ),
    ]
